---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: nodejs-16-example
  name: nodejs-16-example
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: nodejs-16-example
  name: nodejs-16-example
spec:
  source:
    binary: {}
  output:
    to:
      kind: ImageStreamTag
      name: nodejs-16-example:latest
  strategy:
    dockerStrategy: {}
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: nodejs-16-example
  labels:
    app: nodejs-16-example
spec:
  template:
    metadata:
      labels:
        name: nodejs-16-example
    spec:
      containers:
        - name: nodejs-16-example
          image: nodejs-16-example
          ports:
            - containerPort: 8080
  replicas: 1
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - nodejs-16-example
        from:
          kind: ImageStreamTag
          name: nodejs-16-example:latest
  strategy:
    type: Rolling
  paused: false
  revisionHistoryLimit: 5
  minReadySeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-16-example
    application: nodejs-16-example
  name: nodejs-16-example
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: nodejs-16-example
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: nodejs-16-example
    application: nodejs-16-example
  name: nodejs-16-example
spec:
  to:
    kind: Service
    name: nodejs-16-example
    weight: 100

